spring.output.ansi.enabled: ALWAYS

server.port: 9090
security:
 oauth2:
   resource:
   # userInfoUri: http://localhost:8080/auth/user
     jwt:
       keyUri: http://localhost:8080/auth/oauth/token_key